/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : SVG Converter
 #	author : miyako
 #	2013/09/27
 #
 # --------------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>

#include <rsvg.h>
#include <rsvg-css.h>
#include <rsvg-size-callback.h>

#include <cairo-ps.h>
#include <cairo-pdf.h>
#include <cairo-svg.h>
#ifndef WIN32
#include <cairo-quartz.h>
#else
#include "Shlwapi.h"
#include "WinInet.h"
#endif
#include <cairo-xml.h>

// --- Convert Many
void SVG_Convert_array(sLONG_PTR *pResult, PackagePtr pParams);

// --- Convert One
void SVG_Convert(sLONG_PTR *pResult, PackagePtr pParams);

// --- URL
void URL_Convert_from_path(sLONG_PTR *pResult, PackagePtr pParams);
void URL_Convert_to_path(sLONG_PTR *pResult, PackagePtr pParams);

#define SVG_DPI_X 1
#define SVG_DPI_Y 2
#define SVG_ZOOM_X 3
#define SVG_ZOOM_Y 4
#define SVG_ZOOM 5
#define SVG_WIDTH 6
#define SVG_HEIGHT 7
#define SVG_KEEP_ASPECT_RATIO 8

#define SVG_OUTPUT_PDF 0
#define SVG_OUTPUT_PNG 1
#define SVG_OUTPUT_PS 2
#define SVG_OUTPUT_SVG 3
